### ISSUE TITLE
Please NO OPENING

### ISSUE THREAD

**Issue by Froktime** [abdlhay/AbyssVideoDownloader#1]
You're challenging Abyss, they're fixing it constantly. Continuous encryption. Please, **stop, stop, stop**. You're doing something that makes their encryption stronger and won't be able to download anymore. If you know how to download video, download it for yourself. Don't share it publicly!!!!

**Comment by Froktime** [comment]
https://github.com/PatrickL546/Hydrax-Abyss.to-DownloadHelper-Python/issues/10
Please close this source code

**Comment by Froktime** [comment]
See this.
https://github.com/PatrickL546/Hydrax-Abyss.to-DownloadHelper-Python/issues/10
Please close your source code

**Comment by mustafacakirogludev** [comment]
So you are basically saying "I know how to do it, who cares about the others". Thank you abdlhay for providing this repo, much appreciated, don't mind this selfish person.

**Comment by sadtango289** [comment]
full of selfishness

**Comment by Froktime** [comment]
> full of selfishness

if Abyss didn't keep fixing it so many times I wouldn't be selfish, I'm selfish but it helps me download well. have you seen Netflix? why doesn't anyone share how to download publicly anymore. I just don't want to open it publicly like that because they can easily see and fix it. If it's shared privately, I agree. if you think about the future, they encrypt stronger and harder to find ways to download then you will see this as a short term solution.

**Comment by sadtango289** [comment]
> > full of selfishness
> 
> if Abyss didn't keep fixing it so many times I wouldn't be selfish, I'm selfish but it helps me download well. have you seen Netflix? why doesn't anyone share how to download publicly anymore. I just don't want to open it publicly like that because they can easily see and fix it. If it's shared privately, I agree. if you think about the future, they encrypt stronger and harder to find ways to download then you will see this as a short term solution.

I think the admin completely realized this from the beginning, when Abyss continuously fixed , but maybe, for some personal reason, he continued until now. 

Whatever. This is the battle of the coders. You are professional. You will break all barriers soon. I'm a ''low-tech'' person, for me (and almost people) - internet is sharing - having it is good, but not having it is also okay.

**Comment by thongnq0906** [comment]
> > full of selfishness
> 
> if Abyss didn't keep fixing it so many times I wouldn't be selfish, I'm selfish but it helps me download well. have you seen Netflix? why doesn't anyone share how to download publicly anymore. I just don't want to open it publicly like that because they can easily see and fix it. If it's shared privately, I agree. if you think about the future, they encrypt stronger and harder to find ways to download then you will see this as a short term solution.

telegram you? please
