### ISSUE TITLE
not working for my video id

### ISSUE THREAD

**Issue by VLiulian** [abdlhay/AbyssVideoDownloader#14]
Hello, it's a great comand line app, and it works very well in most cases. But not for this I'd: Kj1HAeAde, it return time out error.
My system Debian 12.

Thanks for the script!

**Comment by abdlhay** [comment]
Hi,
Some videos require specifying a header to work, usually the Referer or Origin header.
You can find which headers are used by inspecting the requests made from the browser's developer tools.

**Comment by VLiulian** [comment]
Hi, 
It is a series, and it works for all episodes, except 13 this one. And I don't find any headers. 
https:// catoonhub.com/series/346/2/13

**Comment by abdlhay** [comment]
It works on my end when I run the following:  
```bash
java -jar abyss-dl.jar Kj1HAeAde  
```  

I’ve tested it on multiple machines, and as you mentioned earlier, the timeout exception seems to be a network-related issue.  

Additionally, I’ve added `catoonhub` to the list of supported providers. For future use, you can directly add the URL like this:  
```bash
java -jar abyss-dl.jar https://catoonhub.com/series/346/2/13  
```

**Comment by VLiulian** [comment]
Ok, thank you for adding catoonhub, and your time !
I will try on author machine or connection.
