### ISSUE TITLE
Parallel downloads

### ISSUE THREAD

**Issue by mustafacakirogludev** [abdlhay/AbyssVideoDownloader#2]
Hey, thank you so much for this repo. I was just wondering, is there a way to paralel download a single file as multiple parts so its faster? Right now it works albeit slow.

**Comment by abdlhay** [comment]
Yes, I’ve been considering this as well, I’ll go ahead and implement it

**Comment by abdlhay** [comment]
I’ve implemented parallel downloads Please let me know if you encounter any issues.

By default, the app uses **6 connections** for downloads, but you can adjust this using the `-c` argument to set the number of connections to your preference.

**Comment by mustafacakirogludev** [comment]
It works perfectly for me, thank you for your time!
