### ISSUE TITLE
Implement Batch Download Feature for Multiple Videos

### ISSUE THREAD

**Issue by kukhanh29** [abdlhay/AbyssVideoDownloader#4]
https://www.oracle.com/java/technologies/javase/jdk21-archive-downloads.html
I am using Ubuntu, which version should I use to run Java commands?

how to make it run like this instead of having to add another command to enter:
java -jar abyss-dl.jar --header "Referer: https://abyss.to/" [quality_1080p] [ID_abyss]

**Comment by abdlhay** [comment]
You can easily install JDK 21 on Ubuntu by running the following command:

```bash
sudo apt install openjdk-21-jdk -y
```

As for your second request, could you provide more details on why you need to run it in that specific way? Are you looking to download videos in batch using a Bash script, or is there another particular reason for your approach?

**Comment by kukhanh29** [comment]
thank you for your support.
because I want to download many links. the current download method can only download 1 link and it is difficult to write a command to automatically download.

**Comment by abdlhay** [comment]
Ah, I see. Don't worry about that I'll add a way to download videos in batches
