### ISSUE TITLE
How do I specify output path ? 

### ISSUE THREAD

**Issue by sadtango289** [abdlhay/AbyssVideoDownloader#5]
Hi. I'm a low-tech. Please use simple words. 
1. I don't understand about how to set folder for save videos. Please make an example with my folder E:\video ( -o /path/to/directory/my_video.mp4 - I don't understand ) 
2. What is this bug ? 
![Screenshot 2024-10-30 041822](https://github.com/user-attachments/assets/a5918e09-cbce-4e97-b419-9db1c8f0cce1)

**Comment by abdlhay** [comment]
```bash
java -jar abyss-dl.jar -o E:\video\video_name.mp4
```
with the command above your video will be saved at `E:\video` with the name you choose `video_name.mp4`

if you didn't specify path the video will be save at where you run the jar file with generated name `id_resolution_currentTimeStamp.mp4`

`-o /path/to/directory/my_video.mp4` was just an example
