### ISSUE TITLE
My previous problem has not been considered. Please.

### ISSUE THREAD

**Issue by sadtango289** [abdlhay/AbyssVideoDownloader#6]
What is this bug ? 

![381313507-a5918e09-cbce-4e97-b419-9db1c8f0cce1](https://github.com/user-attachments/assets/355b3ee2-29d6-4028-b1f0-53f83813f98b)

**Comment by abdlhay** [comment]
please post the command input you used
and what's your Operating system.
also I see you running cmd as Administrator

**Comment by sadtango289** [comment]
Windows 10 Pro
Version	22H2
Installed on	‎9/‎15/‎2023
OS build	19045.5073
Experience	Windows Feature Experience Pack 1000.19060.1000.0

i input java -jar abyss-dl.jar 
i input video id 
and result as below 
![Screenshot 2024-11-04 203104](https://github.com/user-attachments/assets/bf41c01f-03b7-44df-9a51-2e3a9e022bca)
![Screenshot 2024-11-04 203333](https://github.com/user-attachments/assets/c284b568-1396-4c3b-aae8-e3ca7d838e01)

**Comment by abdlhay** [comment]
You are trying to run and save a video in a restricted path, Program Files, which is accessible only by the administrator. Please navigate to a common user folder, such as Desktop or Downloads, and run the JAR file there.
